iop4api/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "iop4api"

class TabsConverter:
    regex = '.*'

    def to_python(self, value):
        return value.split('/')

    def to_url(self, value):
        return '/'.join(value)
    
from django.urls import register_converter
register_converter(TabsConverter, 'tabs')

urlpatterns = []

if settings.DEBUG:
    # local docs only accesible in debug server, in production you should 
    # configure it yourself (if you want it to be public, etc)
    urlpatterns += [path(r'docs/', views.docs, name='docs')]
    urlpatterns += [path(r'docs/<path:file_path>', views.docs)]


urlpatterns = urlpatterns + [
    path('', views.index, name='index'),
    path('api/login/', views.login_view, name='login_view'),
    path('api/logout/', views.logout_view, name='logout_view'),
    path('api/plot/', views.plot, name='plot'),
    path('api/data/', views.data, name='data'),
    path('api/catalog/', views.catalog, name='catalog'),
    path('api/log/', views.log, name='log'),
    path('api/flag/', views.flag, name='flag'),
    path('<tabs:tabs>/', views.index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

iop4api/views/catalog.py
# iop4lib config
import iop4lib
iop4conf = iop4lib.Config(config_db=False)


# django imports
from django.http import JsonResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import permission_required
from django.db import models

# iop4lib imports
from iop4lib.db import AstroSource
from iop4lib.enums import SRCTYPES
from iop4lib.utils import qs_to_table

# other imports

#logging
import logging
logger = logging.getLogger(__name__)

# API VIEWS



@permission_required(["iop4api.view_astrosource"])
def catalog(request):
    qs = AstroSource.objects.exclude(is_calibrator=True)

    all_column_names = [f.name for f in AstroSource._meta.get_fields() if hasattr(f, 'verbose_name')]

    return JsonResponse(qs_to_table(qs=qs, column_names=all_column_names))

iop4api/views/data.py
# iop4lib config
import iop4lib
iop4conf = iop4lib.Config(config_db=False)

# django imports
from django.http import JsonResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import permission_required
from django.db import models

# iop4lib imports
from iop4lib.db import AstroSource, PhotoPolResult
from iop4lib.utils import qs_to_table

# other imports
from astropy.time import Time

#logging
import logging
logger = logging.getLogger(__name__)


@permission_required(["iop4api.view_photopolresult", "iop4api.view_astrosource"], raise_exception=True)
def data(request):

    source_name = request.POST.get("source_name", None)

    if not AstroSource.objects.filter(name=source_name).exists(): 
        return HttpResponseBadRequest(f"Source '{source_name}' does not exist")
    
    qs = PhotoPolResult.objects.filter(astrosource__name=source_name)

    data = qs.values()

    all_column_names = data[0].keys()
    default_column_names = ['juliandate', 'instrument', 'band', 'mag', 'mag_err', 'p', 'p_err', 'chi', 'chi_err']

    table_and_columns = qs_to_table(data=data, model=PhotoPolResult, column_names=all_column_names, default_column_names=default_column_names)
    
    result = {
                "data": table_and_columns["data"],
                "columns": table_and_columns["columns"],
                "query": {
                            "source_name": source_name, 
                            "count": qs.count()
                        }
    }

    # annotate with date from the julian date
    for r in result["data"]:
        r["date"] = Time(r["juliandate"], format='jd').iso
    result["columns"].append({"name": "date", "title": "date", "type": "date", "help": "date and time in ISO 8601 format, from the julian date"})    

    # annotate with flag labels
    for r in result["data"]:
        r["flag_labels"] = ",".join(PhotoPolResult.FLAGS.get_labels(r["flags"]))
    result["columns"].append({"name": "flag_labels", "title": "flag labels", "type": "string", "help": "flags as human readable labels"})

    return JsonResponse(result)

iop4api/views/log.py
# iop4lib config
import iop4lib
iop4conf = iop4lib.Config(config_db=False)

# django imports
from django.http import StreamingHttpResponse, HttpResponse
from django.contrib.auth.decorators import permission_required
from django.contrib.admin.views.decorators import staff_member_required

# iop4lib imports

# other imports
import coloredlogs
import coloredlogs.converter
from pathlib import Path

#logging
import logging
logger = logging.getLogger(__name__)


def get_log_file_generator(fpath):
    def _log_file_generator():
        with open(fpath, "r") as f:
            for line in f:
                yield coloredlogs.converter.convert(line)
    return _log_file_generator()

@staff_member_required
@permission_required(["iop4api.view_photopolresult", "iop4api.view_astrosource"], raise_exception=True)
def log(request):
    r"""Staff member required. Since the log file can be very large, we use a generator to stream it to the client."""

    if (log_fname := request.GET.get("log_file", None)):
        fpath = Path(iop4conf.datadir) / "logs" / log_fname
    else:
        fpath = Path(iop4conf.log_file)

    fpath = fpath.resolve()

    if not fpath.is_relative_to(Path(iop4conf.datadir) / "logs"):
        return HttpResponse("Access denied.", status=403)

    if not fpath.exists():
        return HttpResponse("Log file not found.", status=404)
    
    return StreamingHttpResponse(get_log_file_generator(fpath), content_type="text/plain")

iop4api/views/plot.py
# iop4lib config
import iop4lib
iop4conf = iop4lib.Config(config_db=False)


# django imports
from django.http import JsonResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import permission_required

# iop4lib imports
from iop4lib.db import PhotoPolResult, AstroSource
from iop4lib.utils import get_column_values

# other imports
import os
import glob
import numpy as np
import pandas as pd
from astropy.time import Time
from pathlib import Path

#logging
import logging
logger = logging.getLogger(__name__)


@permission_required(["iop4api.view_photopolresult", "iop4api.view_astrosource"], raise_exception=True)
def plot(request):

    source_name = request.POST.get("source_name", None)
    band = request.POST.get("band", "R")
    date_start = request.POST.get("date_start", None) or None # it might be an empty string, this converts it to None
    date_end = request.POST.get("date_end", None) or None

    enable_crosscheckpts = request.POST.get("enable_crosscheckpts", False)
    enable_full_lc = request.POST.get("enable_full_lc", False)
    enable_errorbars = request.POST.get("enable_errorbars", False)
    use_hostcorrected = request.POST.get("use_hostcorrected", False)

    save_filename = f"IOP4_{source_name}_{band}"

    # comment these lines to allow for empty plot
    if not AstroSource.objects.filter(name=source_name).exists(): 
        return HttpResponseBadRequest(f"Source '{source_name}' does not exist".format(source_name=source_name))
    
    target_src = AstroSource.objects.get(name=source_name)

    logger.debug(f"Serving results for {target_src} band {band} from {date_start} to {date_end}")

    # build plot

    import bokeh.colors
    from bokeh.document import Document
    from bokeh.transform import factor_cmap
    from bokeh.layouts import column, gridplot
    from bokeh.models import CategoricalColorMapper, LinearColorMapper, RangeTool, Range1d, LinearAxis, CustomJS, ColumnDataSource, Whisker, DatetimeAxis, DatetimeTickFormatter, Scatter, Segment, CDSView, GroupFilter, AllIndices, HoverTool, NumeralTickFormatter, BoxZoomTool, DataTable, TableColumn, CategoricalMarkerMapper, CustomJSTransform, CustomJSHover, SaveTool, Toolbar
    from bokeh.plotting import figure, show
    from bokeh.embed import components, json_item
    from bokeh.models import Div, Circle, Column, Row
    from bokeh.plotting import figure
    from bokeh.models import ColumnDataSource, Styles, InlineStyleSheet, GlobalInlineStyleSheet
    from bokeh.transform import factor_cmap, factor_mark, transform
    from bokeh.events import Event, PanStart, PanEnd, Press, PressUp, RangesUpdate
    from bokeh.models.widgets import HTMLTemplateFormatter, NumberFormatter

    lod_threshold = 2000
    lod_factor = 10
    lod_timeout = 500

    # secondary axes values
    @np.vectorize
    def f_x1_to_x2(x1_val):
        return Time(x1_val, format='mjd').datetime
    
    # Get data from DB
    column_names = ['id', 'juliandate', 'band', 'instrument', 'mag', 'mag_err', 'p', 'p_err', 'chi', 'chi_err', 'flags']

    if use_hostcorrected:
        column_names += ['mag_corr', 'mag_corr_err', 'p_corr', 'p_corr_err']

    qs = PhotoPolResult.objects.filter(astrosource__name=source_name, band=band).all()

    if date_start is not None:
        qs = qs.filter(juliandate__gte=Time(date_start).jd)

    if date_end is not None:
        qs = qs.filter(juliandate__lte=Time(date_end).jd)

    # crosscheck data

    if enable_crosscheckpts:

        df_crosscheck = pd.DataFrame(columns=['juliandate', 'mag', 'dmag', 'p', 'p_err', 'chi', 'chi_err', 'instrument'])

        iop3_fpath = str(Path(iop4conf.datadir) / "iop4_crosscheck_data" / "iop3.csv")

        if os.path.exists(iop3_fpath):
            df = pd.read_csv(iop3_fpath)

            df_idx = (df["name_IAU"] == source_name) & (df["filter"] == band)

            if date_start is not None:
                df_idx = df_idx & (df["mjd_obs"] >= Time(date_start).mjd)
            if date_end is not None:
                df_idx = df_idx & (df["mjd_obs"] <= Time(date_end).mjd)

            df = df.loc[df_idx]

            # rename IOP3 dump columns to match PhotoPolResult
            df['juliandate'] = Time(df["mjd_obs"], format="mjd").jd
            df['mag'] = df['Mag']
            df['dmag'] = df['dMag']
            df['chi'] = df['Theta']
            df['chi_err'] = df['dTheta']
            df['p'] = df['P']/100
            df['p_err'] = df['dP']/100
            df['instrument'] = list(map(lambda x: "IOP3-"+x, df["Telescope"]))

            df_crosscheck = pd.concat([df_crosscheck, df], ignore_index=True, join="inner")
        
        dipol_dpath = str(Path(iop4conf.datadir) / "iop4_crosscheck_data" / "dipol")
        
        def get_invariable_str(s):
            return s.replace(' ', '').replace('-','').replace('+','').replace('_','').upper()
    
        for fpath in glob.iglob(f"{dipol_dpath}/*.txt"):

            if get_invariable_str(target_src.name) in get_invariable_str(fpath) or get_invariable_str(target_src.other_names_list[0]) in get_invariable_str(fpath):
                logger.debug(f"Reading {fpath}")

                df = pd.read_csv(fpath, delim_whitespace=True, header=None, 
                                 names=["mjd", "q", "u", "p", "p_err", "chi", "chi_err"],
                                 usecols=range(7), dtype=float)

                if date_start is not None:
                    df = df.loc[df["mjd"] >= Time(date_start).mjd]
                if date_end is not None:
                    df = df.loc[df["mjd"] <= Time(date_end).mjd]

                df['juliandate'] = Time(df["mjd"], format="mjd").jd
                df['mag'] = np.nan
                df['dmag'] = np.nan
                df['p'] = df['p']/100
                df['p_err'] = df['p_err']/100
                df['instrument'] = np.full(len(df), "VILPPU-DIPOL")

                df_crosscheck = pd.concat([df_crosscheck, df], ignore_index=True, join="inner")

    # choose  the x and y
    if qs.count() > 0:
        vals = get_column_values(qs, column_names)
        if use_hostcorrected:
            # just overwrite the values
            vals['mag'] = vals['mag_corr']
            vals['mag_err'] = vals['mag_corr_err']
            vals['p'] = vals['p_corr']
            vals['p_err'] = vals['p_corr_err']
    else:
        vals = {k:np.array([]) for k in column_names}

    if enable_crosscheckpts:
        if len(df_crosscheck) > 0:
            vals["instrument"] = np.append(vals["instrument"], df_crosscheck['instrument'])
            vals["id"] = np.append(vals["id"], -np.arange(len(df_crosscheck))) ## assign negative ids to crosscheck data
            vals["juliandate"] = np.append(vals["juliandate"], df_crosscheck['juliandate'])
            vals["mag"] = np.append(vals["mag"],  df_crosscheck['mag'])
            vals["mag_err"] = np.append(vals["mag_err"], df_crosscheck['dmag'])
            vals["p"] = np.append(vals["p"], df_crosscheck['p'])
            vals["p_err"] = np.append(vals["p_err"], df_crosscheck['p_err'])
            vals["chi"] = np.append(vals["chi"], df_crosscheck['chi'])
            vals["chi_err"] = np.append(vals["chi_err"], df_crosscheck['chi_err'])
            vals["flags"] = np.append(vals["flags"], np.full(len(df_crosscheck), 0)) # do not show flags for crosscheck data (0 means no flags)

    if len(vals['id']) > 0:
        pks = vals['id']
        x1 = Time(vals['juliandate'], format='jd').mjd
        x2 = f_x1_to_x2(x1)
        y1 = vals['mag']
    else: # to allow empty plot
        vals = {k:np.array([]) for k in column_names}
        pks = np.array([])
        x1 = np.array([])
        x2 = np.array([])
        y1 = np.array([])

    # Instruments and colors (auto)
    instruments_L = sorted(list(set(vals['instrument'])), reverse=True)

    #instrument_color_L = [bokeh.palettes.TolRainbow[max(3,len(instruments_L))][i % len(instruments_L)] for i in range(len(instruments_L))]
    instrument_color_L = [bokeh.palettes.Category10[max(3,len(instruments_L))][i % len(instruments_L)] for i in range(len(instruments_L))]

    rgb_L = [bokeh.colors.RGB.from_hex_string(hexcolor) for hexcolor in instrument_color_L]

    hsl_L_nonselected = [rgb.to_hsl() for rgb in rgb_L]
    hsl_L_selected= [rgb.to_hsl() for rgb in rgb_L]

    for hsl in hsl_L_nonselected:
        # make non-selected colors lighter and more gray
        hsl.l = 0.8
        hsl.s = 0.5

    for hsl in hsl_L_selected:
        hsl.l = 0.5
    
    palette_selected = [bokeh.colors.RGB.from_hsl(hsl) for hsl in hsl_L_selected]
    palette_nonselected = [bokeh.colors.RGB.from_hsl(hsl) for hsl in hsl_L_nonselected]
    
    index_cmap_selected = factor_cmap('instrument', 
                             palette=palette_selected, 
                             factors=instruments_L)
    
    index_cmap_nonselected = factor_cmap('instrument', 
                                   palette=palette_nonselected, 
                                   factors=instruments_L)
    
    # # Flags and markers

    markermap = transform("flags", CustomJSTransform(v_func="""
            let markers = [];
            
            for (let i = 0; i < xs.length; i++) {
                                                     
                let marker = "circle";
                                                                                          
                if (xs[i] & (1 << 1)) { // bad photometry
                    marker = "triangle";
                } 

                if (xs[i] & (1 << 2)) { // bad polarimetry
                    marker = "inverted_triangle";
                }

                if ((xs[i] & (1 << 1)) && (xs[i] & (1 << 2))) { // bad photometry and polarimetry
                    marker = "cross";                                 
                }
                                                                                                                       
                markers.push(marker);
            }   

iop4api/templates/iop4api/about.html
<div class="header">
    <h1>About &nbsp;<span class="material-icons-outlined">rocket_launch</span></h1>
    {% comment %} <h1>About &nbsp;<q-icon name="rocket_launch"></q-icon></h1>  {% endcomment %}
</div>
<div class="content">
    <p>
        IOP4, <i>the Interactive Photo-Polarimetric Python Pipeline</i>. 
        Check <a href="https://github.com/juanep97/iop4">the code in GitHub</a>. 
        Documentation for the last version is hosted in <a href="https://juanep97.github.io/iop4/">GitHub Pages</a>.
    </p>
    
    {% if debug %}
        <p>
            You can browse your local version of the docs at 
            <a href="{% url 'iop4api:docs' %}">/iop4/docs/</a>
            (you need to build it first with make <code>docs-sphinx</code>).
        </p>
    {% endif %}

    {% if request.user.is_authenticated %}
        <p class="styled-box">
            This site is currently running IOP4 <i>{{ git_branch }} @ <a href="https://github.com/juanep97/iop4/commit/{{ git_commit_hash }}">{{ git_describe }}</a></i>.<br>
            <br>
            <span style="font-size:small;">
                This message is visible only to authenticated users.
            </span>
        </p>
    {% endif %}
    
    {% if debug and request.user.is_authenticated %}
        <p class="styled-box">
            It appears that you are running this site in the <span style="color: red;">DEBUG</span> server.<br>
            <br>
            <span style="font-size: small;">
                If this is the case, you can safely ignore this message. 
                Otherwise, check <a href="https://github.com/juanep97/iop4#as-a-program">IOP4</a> and <a href="https://docs.djangoproject.com/en/dev/ref/django-admin/#runserver">Django</a> docs. 
                This message is visible only to authenticated users.
            </span>
        </p>
    {% endif %}
</div>
<div class="footer">
    <p>Created by Juan Escudero Pedrosa for the VHEGA@IAA-CSIC group.</p>
</div>

iop4api/templates/iop4api/catalog.html
<div class="header">
    <h1>Catalog</h1>
</div>
<div class="content">
    <q-table v-if="catalog != null" :rows="catalog.data" :columns="catalog.columns" row-key="id" @row-click="catalog_row_clicked"></q-table>
</div>
<div class="header">
</div>

iop4api/templates/iop4api/data.html
<form id="data_astrosource_form" class="centered styled-box"  style="padding:16px;" onsubmit="load_source_datatable(this); return false;">
    {% csrf_token %}
    <div class="form-row wrappable">
        <label>Select a source from the catalog:</label>
        <div class="f-row">
            <input v-model="input_astrosource"  type="text" name="source_name" list="source_name_list" placeholder="source (↓ to list)" title="Select a source from the catalog" required>
            <input class="button inline" type="button" value="query" onclick="load_source_datatable(this.form);">
        </div>
    </div>
</form>
<div v-show="showDataTable" id="tableControlsContainer">
    <button class="button" id="download-csv">Download as csv</button>
    <button class="button" id="download-pdf">Download as pdf</button>
    <label style="display: flex; align-items: center; gap: 4px;"><input type="checkbox" id="download-include-helptext" name="download-include-helptext" />include columns help</label>
    <button class="button" id="column-visibilities" onclick="show_column_visibility_modal_form()">Toggle columns</button>
    <button class="button" id="table-filters" @click="showDataTableFilters=true;">Set filters</button>
    <!-- Column modal form -->
    <div id="column_visibility_modal_form" class="modal">
        <div class="modal-content">
            <div class="modal_header"><span class="close" onclick="close_column_visibility_modal_form()">&times; Close</span></div>
            <div class="modal_body"><p>modal body</p></div>
            <div class="modal_footer"></div>
        </div>
    </div>
    <!-- ################## -->
    <!-- filter dialog -->
    <q-dialog v-model="showDataTableFilters">
        <q-card v-if="DataTableFilters.length == 0" flat bordered>
            <q-card-section class="row items-center q-gutter-sm" flat bordered>
                <q-item-label class="col-12 col-md-auto">No filters yet</q-item-label>
                <q-btn label="add a new filter" color="primary" class="col-12 col-md-auto" @click="DataTableFilters.push({'field':'','type':'','value':''})"></q-btn>
            </q-card-section>
        </q-card>
        <q-markup-table v-if="DataTableFilters.length != 0" style="max-width: 95vw !important;">
            <table id="FiltersTable">
                <thead>
                    <tr>
                        <!--<th>CDS index</th>-->
                        <th>field</th>
                        <th>type</th>
                        <th>value</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(filter, filter_idx) in DataTableFilters" :key="filter_idx">
                        <!-- <td>[[ index ]]</td> -->
                        <td>
                            <select v-model="DataTableFilters[filter_idx].field" class="filter-field">
                                <option v-for="(col, col_idx) in tableData.columns" :key="col_idx" :value="col.name">
                                    [[ col.title ]]
                                </option>
                            </select>
                        </td>
                        <td>                                
                            <select v-model="DataTableFilters[filter_idx].type" class="filter-type">
                                <option value=""></option>
                                <option value="=">=</option>
                                <option value="<"><</option>
                                <option value="<="><=</option>
                                <option value=">">></option>
                                <option value=">=">>=</option>
                                <option value="!=">!=</option>
                                <option value="like">like</option>
                                <option value="after">after date</option>
                                <option value="before">before date</option>
                                <option value="null">null (input value ignored)</option>
                                <option value="notnull">not null (input value ignored)</option>
                            </select>
                        </td>
                        <td><input v-model="DataTableFilters[filter_idx].value" class="filter-value" type="text" placeholder="value to filter" title="Values will be interpreted as in the following order: &#10; 1) null if value is empty; &#10; 2) as a date if the type is 'after date' or 'before date' and the input is in the ISO 8601 date format (yyy/mm/dd); &#10; 3) as a number."></td>
                        <td>
                            <button class="filter-remove" @click="DataTableFilters.splice(filter_idx, 1)"><span class="material-symbols-outlined">delete</span></button>
                            <button class="filter-add" @click="DataTableFilters.splice(filter_idx+1, 0, {'field':'','type':'','value':''})"><span class="material-symbols-outlined">add</span></button>
                        </td>
                    </tr>
                </tbody>
                <!-- <q-table :rows="selected_plot_pts" columns="" row-key="pk"></q-table> -->
            </table>
        </q-markup-table>
    </q-dialog>
    <!-- ############# -->
</div>
<div v-show="showDataTable" id="tableContainerDiv"><div id="tableDiv"></div></div>

iop4api/templates/iop4api/explore.html
<div class="header">
    <h1>Explore data &nbsp;<span class="material-symbols-outlined">&#xE8B6;</span></h1>
    <div>
        <q-tabs v-model="selectedTabs[1]">
            <q-tab name="catalog" label="catalog"></q-tab>
            {% comment %} <q-tab name="query" label="Query"></q-tab> {% endcomment %}
            <q-tab name="plot" label="Plot"></q-tab>
            <q-tab name="data" label="Data"></q-tab>
            <q-tab name="logs" label="logs"></q-tab>
        </q-tabs>
    </div>
</div>

<div id="explore_container" class="tab-container">

    <datalist id="source_name_list">
        {% for srcname, altname in source_name_list %}
            <option value="{{ srcname }}">
                {{ srcname }} {% if altname and srcname != altname %}&nbsp;&nbsp; ({{altname}}){% endif %}
            </option>
        {% endfor %}
    </datalist>

    <div v-show="selectedTabs[1] === 'catalog'" class="tab-content" id="catalog-tab">
        {% include 'iop4api/catalog.html' %}
    </div>
 
    {% comment %} <div v-show="selectedTabs[1] === 'query'" class="tab-content" id="query-tab">
        {% include 'iop4api/query.html' %}
    </div> {% endcomment %}

    <div v-show="selectedTabs[1] === 'plot'" class="tab-content" id="plot-tab">
        {% include 'iop4api/plot.html' %}
    </div>

    <div  v-show="selectedTabs[1] == 'data'" class="tab-content" id="data-tab">
        {% include 'iop4api/data.html' %}
    </div>

    <div v-show="selectedTabs[1] == 'logs'" class="tab-content" id="logs-tab"> 
        {% include 'iop4api/logs.html' %}
    </div>

</div>

{% comment %} <div class="footer">
</div> {% endcomment %}

iop4api/templates/iop4api/login.html
<div class="header">
    <h1>Login &nbsp;<span class="material-icons-outlined">login</span></h1>
</div>
<div class="content">
    <form action="{% url 'iop4api:login_view' %}" class="styled-box centered" method="post" class="centered">
        {% csrf_token %}
        <div class="form-block">
            <label for="username">Username</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-block">
            <label for="password">Password</label>
            <input type="password" name="password" id="password">
        </div>
        {% if request.GET.login_failed %}
            <p style="color: red; margin: 1em auto; text-align: center;">Invalid username or password.</p>
        {% endif %}
        <div class="form-block">
            <input class="button" type="submit" value="Login">
        </div>
    </form>
</div>
<div class="header">
</div>

iop4api/templates/iop4api/logs.html
<div id="logs-tab-content">
    <q-list padding bordered class="rounded-borders">
        <q-expansion-item
          dense
          icon="settings"
          label="Web application log"
        >
            <q-card>
                <q-card-section style="padding: 8px 16px 0 16px;">
                    <div id="webapp-log-content">
                        <div class="log-entry" v-for="entry in logEntries">
                            <span class="log-entry-title">[[ entry.title ]]</span>
                            <span class="log-entry-datetime">[[ entry.dateTime ]]</span>
                            <pre class="log-entry-content">[[ entry.content ]]</pre>
                        </div>
                    </div>
                </q-card-section>
            </q-card>
        </q-expansion-item>
    </q-list>

    <q-list padding bordered class="rounded-borders">
        <q-expansion-item
          dense
          icon="settings"
          label="Pipeline log"
          default-opened
        >
            <q-card>
                <q-card-section style="padding: 8px 16px 0 16px;">
                    <div class="row items-center q-gutter-sm">
                        <q-select
                            v-model="log_file"
                            :options="log_files"
                            dense
                        ></q-select>
                        <q-chip @update:selected="() => $nextTick(format_pipeline_logs)" v-model:selected="pipeline_log_options.errors" color="red" text-color="white" icon="error" :outline="!pipeline_log_options.errors">
                            errors
                        </q-chip>
                        <q-chip @update:selected="() => $nextTick(format_pipeline_logs)" v-model:selected="pipeline_log_options.warnings" color="orange" text-color="white" icon="warning" :outline="!pipeline_log_options.warnings">
                            warning
                        </q-chip>
                        <q-chip @update:selected="() => $nextTick(format_pipeline_logs)" v-model:selected="pipeline_log_options.info" color="darkgray" text-color="black" icon="info" :outline="!pipeline_log_options.info">
                            info
                        </q-chip>
                        <q-chip @update:selected="() => $nextTick(format_pipeline_logs)" v-model:selected="pipeline_log_options.debug" color="green" text-color="white" icon="code" :outline="!pipeline_log_options.debug">
                            debug
                        </q-chip>
                        <input type="text" @change="format_pipeline_logs();" v-model="pipeline_log_options.filter_text" placeholder="filter text (+ Enter)" class="q-chip row inline no-wrap items-center text-black q-chip--colored q-chip--outline" style="outline: none;">
                        <q-spinner
                            v-show="pipeline_log.filter_in_progress"
                            color="primary"
                            size="1em"
                            :thickness="10"
                        ></q-spinner>
                    </div>
                    <div id="pipeline-logs-tab-content">
                        <div id="log-file-content">
                            <q-virtual-scroll :items="pipeline_log.items_filtered" style="height: 100%;" virtual-scroll-item-size="14" separator v-slot="{ item, index }">
                                <q-item :key="index" dense class="pipeline-log-entry">
                                    <q-item-section  class="pipeline-log-entry">
                                        <q-item-label class="pipeline-log-entry">
                                            <span class="pipeline-log-entry" v-html="item"></span>
                                        </q-item-label>
                                        </q-item-section>
                                    </q-item>
                            </q-virtual-scroll>   
                        </div>
                    </div>
                </q-card-section>
            </q-card>
        </q-expansion-item>
    </q-list>


</div>

iop4api/templates/iop4api/query.html
<form id="query_astrosource_form" class="styled-box centered"  onsubmit="load_source_plot(this); load_source_datatable(this); return false;">
    {% csrf_token %}
    <div>
        <div class="form-block">
            <label>Select a source from the catalog:</label>
            <input v-model="input_astrosource" type="text" name="source_name" list="source_name_list" placeholder="source (↓ to list)" title="Select a source from the catalog" required>
        </div>
        <div class="form-block">
            <div class="form-row">
                <input class="button" type="button" value="plot" onclick="load_source_plot(this.form);">
                <input class="button" type="button" value="query" onclick="load_source_datatable(this.form);">
            </div>
        </div>
    </div>
</form>